### PR TITLE
International request

### PR DESCRIPTION
**Pull request by juradee**
Add option to set up sender address for international requests.

- [ ] Has test coverage.
- [ ] No errors detected when running `make`.
- [ ] Code formatting is in order (done with `make` or `make ci`).

### CODE REVIEW

**Comment by sanmai** [comment]
Thank you for the PR! 

Could you tell where did these `receiverCityCountryCode` and `receiverCity` (and two others) came from? I'm [looking at the docs](https://confluence.cdek.ru/pages/viewpage.action?pageId=20264477) and see nothing like these.

**Comment by juradee** [comment]
1.5 | October 28, 2019 | New filter weightmin has been added in the method "Loading the List of Pickup Points"New fileds have been added in the calculator methods for identify cities (senderCountryCode, receiverCountryCode, senderCity, receiverCity, senderLongitude, receiverLongitude, senderLatitude, receiverLatitude fields)
-- | -- | --


The description you can find at  4.14.1.1. Description of Data to be Transmitted

**Comment by juradee** [comment]
receiverCityCountryCode and senderCityCountryCode are typos. I will fix it.

**Comment by sanmai** [comment]
No problem. I left a checklist for you. If you can verify and check all boxes, and then tag this as ready for a review, that'll be best.

**Comment by sanmai** [comment]
Merged as part of #98

**Pull request closed without merging**
